package com.blockko.app.ui.strings

/**
 * Every user-facing string used by the Compose UI, in English and Taglish.
 * We intentionally don't rely on Android locale resources for this toggle —
 * it's an explicit in-app switch, independent of the device's system language.
 */
data class BlockKoStrings(
    val appTagline: String,
    // Onboarding
    val onboardingTitle: String,
    val onboardingBody: String,
    val onboardingLocalPoint: String,
    val onboardingLimitsPoint: String,
    val onboardingCta: String,
    // Home / dashboard
    val statusProtected: String,
    val statusPaused: String,
    val statusOff: String,
    val toggleHint: String,
    val pauseAction: String,
    val resumeAction: String,
    val blockedTodayLabel: String,
    val blockedAllTimeLabel: String,
    val queriesTodayLabel: String,
    val chartTitle: String,
    val topBlockedTitle: String,
    val topBlockedEmpty: String,
    val protectedBanner: (Int) -> String,
    val tapToAllowlist: String,
    // Apps screen
    val appsTitle: String,
    val appsSubtitle: String,
    val appsBankingHint: String,
    val appsSearchHint: String,
    // Blocklist screen
    val blocklistTitle: String,
    val blocklistUpdateAction: String,
    val blocklistLastUpdated: (String) -> String,
    val blocklistDomainCount: (Int) -> String,
    val blocklistUpdating: String,
    val blocklistUpdateSuccess: (Int) -> String,
    val blocklistUpdateFailed: String,
    val customRulesTitle: String,
    val addBlockRule: String,
    val addAllowRule: String,
    val customRuleHint: String,
    val searchHint: String,
    // Settings
    val settingsTitle: String,
    val settingsUpstreamDns: String,
    val settingsLanguage: String,
    val settingsAutoStart: String,
    val settingsAutoStartHint: String,
    val settingsBatteryOptimization: String,
    val settingsBatteryOptimizationHint: String,
    val settingsAbout: String,
    // About / limitations
    val aboutTitle: String,
    val limitationsTitle: String,
    val limitationInAppAds: String,
    val limitationSingleVpn: String,
    val limitationPrivateDns: String,
    val limitationIpv6: String
)

val EnglishStrings = BlockKoStrings(
    appTagline = "Local, private DNS ad blocking",
    onboardingTitle = "Welcome to BlockKo",
    onboardingBody = "BlockKo filters ads and trackers for every app on this device using a small local filter — not a remote VPN server.",
    onboardingLocalPoint = "No data ever leaves your phone to a third-party server. Filtering happens entirely on-device.",
    onboardingLimitsPoint = "Android will show a \"connected to VPN\" icon — that's expected. It just lets BlockKo see DNS requests to filter them.",
    onboardingCta = "Enable Protection",
    statusProtected = "Protected",
    statusPaused = "Paused",
    statusOff = "Off",
    toggleHint = "Tap to toggle protection",
    pauseAction = "Pause 5 min",
    resumeAction = "Resume",
    blockedTodayLabel = "Blocked today",
    blockedAllTimeLabel = "Blocked all-time",
    queriesTodayLabel = "Queries today",
    chartTitle = "Blocked, last 7 days",
    topBlockedTitle = "Top blocked domains",
    topBlockedEmpty = "Nothing blocked yet — browse around and check back here.",
    protectedBanner = { count -> "You're protected! $count ads blocked today." },
    tapToAllowlist = "Tap a domain to allow it",
    appsTitle = "App exclusions",
    appsSubtitle = "Apps you exclude bypass BlockKo entirely and use your normal connection.",
    appsBankingHint = "Tip: consider excluding banking apps",
    appsSearchHint = "Search apps",
    blocklistTitle = "Blocklist",
    blocklistUpdateAction = "Update blocklist",
    blocklistLastUpdated = { date -> "Last updated: $date" },
    blocklistDomainCount = { count -> "$count domains blocked" },
    blocklistUpdating = "Downloading and parsing…",
    blocklistUpdateSuccess = { count -> "Updated — $count domains loaded" },
    blocklistUpdateFailed = "Update failed. Check the URL and your connection.",
    customRulesTitle = "Custom rules",
    addBlockRule = "Block a domain",
    addAllowRule = "Allow a domain",
    customRuleHint = "e.g. ads.example.com",
    searchHint = "Search rules",
    settingsTitle = "Settings",
    settingsUpstreamDns = "Upstream DNS",
    settingsLanguage = "Language",
    settingsAutoStart = "Auto-start on boot",
    settingsAutoStartHint = "Reconnect protection automatically after your phone restarts",
    settingsBatteryOptimization = "Battery optimization",
    settingsBatteryOptimizationHint = "Exclude BlockKo from battery optimization so it isn't killed in the background",
    settingsAbout = "About & limitations",
    aboutTitle = "About BlockKo",
    limitationsTitle = "Honest limitations",
    limitationInAppAds = "In-app ads inside apps like YouTube or Facebook are mostly NOT blockable via DNS — those ads are served from the same domains as the app's core content.",
    limitationSingleVpn = "Only one VPN can run at a time on Android. BlockKo cannot run alongside another VPN app.",
    limitationPrivateDns = "If Private DNS (DNS-over-TLS) is enabled in your system settings, some queries may bypass BlockKo. Set Private DNS to Off or Automatic for full protection.",
    limitationIpv6 = "BlockKo currently filters IPv4 DNS traffic. On networks that hand out IPv6 DNS servers, some queries may not be filtered."
)

val TaglishStrings = BlockKoStrings(
    appTagline = "Local at private na DNS ad blocker",
    onboardingTitle = "Welcome sa BlockKo!",
    onboardingBody = "Ino-block ng BlockKo ang ads at trackers para sa lahat ng apps sa device mo gamit ang local filter — hindi remote VPN server.",
    onboardingLocalPoint = "Walang data na lumalabas sa third-party server. Nangyayari lahat 'to sa loob ng phone mo.",
    onboardingLimitsPoint = "Magpapakita ang Android ng \"connected to VPN\" icon — normal lang 'yan. Kailangan 'yan para makita ng BlockKo ang DNS requests para ma-filter.",
    onboardingCta = "I-enable ang Proteksyon",
    statusProtected = "Protektado",
    statusPaused = "Naka-pause",
    statusOff = "Naka-off",
    toggleHint = "I-tap para i-toggle ang proteksyon",
    pauseAction = "I-pause ng 5 min",
    resumeAction = "Ituloy",
    blockedTodayLabel = "Na-block ngayong araw",
    blockedAllTimeLabel = "Na-block lahat-lahat",
    queriesTodayLabel = "Queries ngayong araw",
    chartTitle = "Na-block, huling 7 araw",
    topBlockedTitle = "Pinaka-blocked na domains",
    topBlockedEmpty = "Wala pang na-block — mag-browse ka muna at balikan mo 'to.",
    protectedBanner = { count -> "Protektado ka na! $count ads ang na-block today." },
    tapToAllowlist = "I-tap ang domain para i-allow",
    appsTitle = "App exclusions",
    appsSubtitle = "Ang apps na i-exclude mo ay lalampas sa BlockKo at gagamit ng normal na koneksyon.",
    appsBankingHint = "Tip: i-consider i-exclude ang mga banking apps",
    appsSearchHint = "Maghanap ng app",
    blocklistTitle = "Blocklist",
    blocklistUpdateAction = "I-update ang blocklist",
    blocklistLastUpdated = { date -> "Huling na-update: $date" },
    blocklistDomainCount = { count -> "$count domains ang naka-block" },
    blocklistUpdating = "Dina-download at ino-organize…",
    blocklistUpdateSuccess = { count -> "Na-update — $count domains ang na-load" },
    blocklistUpdateFailed = "Hindi na-update. I-check ang URL at connection mo.",
    customRulesTitle = "Custom na rules",
    addBlockRule = "Mag-block ng domain",
    addAllowRule = "Mag-allow ng domain",
    customRuleHint = "hal. ads.example.com",
    searchHint = "Maghanap ng rules",
    settingsTitle = "Settings",
    settingsUpstreamDns = "Upstream DNS",
    settingsLanguage = "Wika",
    settingsAutoStart = "Auto-start pag naka-boot",
    settingsAutoStartHint = "Automatic na babalik ang proteksyon pagkatapos mag-restart ng phone",
    settingsBatteryOptimization = "Battery optimization",
    settingsBatteryOptimizationHint = "I-exclude ang BlockKo sa battery optimization para hindi ito ma-kill sa background",
    settingsAbout = "Tungkol sa app & limitations",
    aboutTitle = "Tungkol sa BlockKo",
    limitationsTitle = "Totoong limitations",
    limitationInAppAds = "Ang in-app ads sa loob ng apps tulad ng YouTube o Facebook ay kadalasang HINDI mabbloblock via DNS — galing kasi 'yan sa parehong domain ng core content ng app.",
    limitationSingleVpn = "Isang VPN lang ang pwedeng tumakbo sa isang pagkakataon sa Android. Hindi pwede sabay-sabay ang BlockKo sa ibang VPN app.",
    limitationPrivateDns = "Kung naka-enable ang Private DNS (DNS-over-TLS) sa system settings mo, may mga query na maaaring makaiwas sa BlockKo. I-set sa Off o Automatic ang Private DNS para sa full protection.",
    limitationIpv6 = "Sa ngayon, IPv4 DNS traffic lang ang na-filter ng BlockKo. Sa networks na gumagamit ng IPv6 DNS servers, may mga query na hindi ma-filter."
)
